all:
	pylint --disable duplicate-code,wrong-import-order,use-dict-literal,too-many-lines,wildcard-import,invalid-name,use-list-literal-missing-module-docstring,line-too-long,use-list-literal,wrong-import-position,unused-wildcard-import,missing-module-docstring,missing-function-docstring ??-?
