#!/usr/bin/env python3

def elfgame(startingseq, finish):
    """
    >>> elfgame("0,3,6", 10)
    0
    >>> elfgame("0,3,6", 2020)
    436
    >>> elfgame("1,3,2", 2020)
    1
    >>> elfgame("2,1,3", 2020)
    10
    >>> elfgame("1,2,3", 2020)
    27
    >>> elfgame("2,3,1", 2020)
    78
    >>> elfgame("3,2,1", 2020)
    438
    >>> elfgame("3,1,2", 2020)
    1836
    """

    last_said_when = dict()
    starts = map(int, startingseq.split(","))
    
    for i, n in enumerate(starts):
        v = last_said_when.get(n)
        last_said_when[n] = i

    for i in range(i+1, finish):
        if v is not None:
            n = i - v - 1
        else:
            n = 0

        v = last_said_when.get(n)
        last_said_when[n] = i

    return n

import doctest
doctest.testmod()

print(elfgame("15,5,1,4,7,0", 2020))
print(elfgame("15,5,1,4,7,0", 30000000))
