#!/usr/bin/python3

import re
import itertools
import doctest
from collections import Counter

exdoc = """3,4,3,1,2"""

doc = """4,1,3,2,4,3,1,4,4,1,1,1,5,2,4,4,2,1,2,3,4,1,2,4,3,4,5,1,1,3,1,2,1,4,1,1,3,4,1,2,5,1,4,2,2,1,1,1,3,1,5,3,1,2,1,1,1,1,4,1,1,1,2,2,1,3,1,3,1,3,4,5,1,2,2,1,1,1,4,1,5,1,3,1,3,4,1,3,2,3,4,4,4,3,4,5,1,3,1,3,5,1,1,1,1,1,2,4,1,2,1,1,1,5,1,1,2,1,3,1,4,2,3,4,4,3,1,1,3,5,3,1,1,5,2,4,1,1,3,5,1,4,3,1,1,4,2,1,1,1,1,1,1,3,1,1,1,1,1,4,5,1,2,5,3,1,1,3,1,1,1,1,5,1,2,5,1,1,1,1,1,1,3,5,1,3,2,1,1,1,1,1,1,1,4,5,1,1,3,1,5,1,1,1,1,3,3,1,1,1,4,4,1,1,4,1,2,1,4,4,1,1,3,4,3,5,4,1,1,4,1,3,1,1,5,5,1,2,1,2,1,2,3,1,1,3,1,1,2,1,1,3,4,3,1,1,3,3,5,1,2,1,4,1,1,2,1,3,1,1,1,1,1,1,1,4,5,5,1,1,1,4,1,1,1,2,1,2,1,3,1,3,1,1,1,1,1,1,1,5"""

def model(state, after_days=80):
    """
    dict numdays -> fishcount
    >>> sum(model(exdoc, 18))
    26
    >>> sum(model(exdoc, 80))
    5934
    >>> sum(model(exdoc, 256))
    26984457539
    """
    state = dict(Counter(sorted(map(int, state.split(",")))).items())
    for day in range(after_days):
        zero_count = state.get(0, 0)
        state = dict((days-1, fishcount) for days, fishcount in state.items() if days > 0)
        state[6] = state.get(6, 0) + zero_count
        state[8] = state.get(8, 0) + zero_count
    return state.values()

import doctest
doctest.testmod(optionflags=doctest.REPORT_UDIFF|doctest.NORMALIZE_WHITESPACE|doctest.ELLIPSIS)

print(sum(model(doc, 256)))
